#!/bin/sh
set -e

# API base URL (REQUIRED - must be set via environment variable)
# In production, this MUST be set to the actual backend API URL
# Examples:
#   - Docker internal: http://backend:3000/api/v1
#   - External API: https://api.yourdomain.com/api/v1
#   - Same domain: https://yourdomain.com/api/v1

# Check if API_BASE_URL is set
if [ -z "$API_BASE_URL" ]; then
  echo "❌ ERROR: API_BASE_URL environment variable is not set!"
  echo "   This is REQUIRED for the application to work."
  echo "   Set it in your docker-compose.yml or .env file:"
  echo "   Example: API_BASE_URL=https://api.yourdomain.com/api/v1"
  exit 1
fi

# Validate that localhost is not used in production
# Detect if we're in production (NODE_ENV or common production indicators)
if [ "$NODE_ENV" = "production" ] || [ -z "$NODE_ENV" ]; then
  # Check if API_BASE_URL contains localhost (case-insensitive)
  case "$API_BASE_URL" in
    *localhost*|*127.0.0.1*)
      echo "❌ ERROR: API_BASE_URL contains localhost/127.0.0.1 which will NOT work in production!"
      echo "   Current value: $API_BASE_URL"
      echo "   localhost refers to the user's browser, not your server."
      echo "   Set API_BASE_URL to your actual backend URL:"
      echo "   Example: API_BASE_URL=https://api.yourdomain.com/api/v1"
      exit 1
      ;;
  esac
fi

# Warn if using localhost in any environment (development should use explicit localhost)
if echo "$API_BASE_URL" | grep -qi "localhost\|127.0.0.1"; then
  echo "⚠️  WARNING: API_BASE_URL contains localhost: $API_BASE_URL"
  echo "   This will only work if the backend is accessible from the browser."
  echo "   For production, use your actual backend domain."
fi

echo "🔧 Generating config.js with API_BASE_URL=${API_BASE_URL}"

# Generate config.js file with runtime configuration
# Escape single quotes and backslashes in API_BASE_URL to prevent script injection
ESCAPED_URL=$(echo "$API_BASE_URL" | sed "s/'/\\\'/g" | sed 's/\\/\\\\/g')
cat > /usr/share/nginx/html/config.js <<EOF
// Runtime configuration injected at container startup
// This file is generated by docker-entrypoint.sh
// DO NOT EDIT MANUALLY - it will be regenerated on container restart
(function() {
  'use strict';
  window.__APP_CONFIG__ = {
    API_BASE_URL: '${ESCAPED_URL}'
  };
  // Log for debugging (only in non-production or if explicitly enabled)
  if (window.console && (window.location.hostname !== 'localhost' || window.location.search.includes('debug=true'))) {
    console.log('✅ Runtime config loaded:', window.__APP_CONFIG__);
  }
})();
EOF

# Set proper permissions
chown nginx:nginx /usr/share/nginx/html/config.js
chmod 644 /usr/share/nginx/html/config.js

# Verify the file was created and has content
if [ -f /usr/share/nginx/html/config.js ]; then
    echo "✅ config.js created successfully"
    echo "📄 config.js contents:"
    cat /usr/share/nginx/html/config.js
    echo ""
    # Verify file is readable
    if [ -r /usr/share/nginx/html/config.js ]; then
        echo "✅ config.js is readable"
    else
        echo "❌ ERROR: config.js is not readable!"
        exit 1
    fi
else
    echo "❌ ERROR: config.js was not created!"
    exit 1
fi

# Execute the main command (nginx)
exec "$@"

