export enum TicketType {
  MAINTENANCE = 'MAINTENANCE',
  SERVICE_REQUEST = 'SERVICE_REQUEST',
  INCIDENT = 'INCIDENT',
  INSPECTION = 'INSPECTION',
  PREVENTIVE = 'PREVENTIVE',
  COMPLAINT = 'COMPLAINT',
}

