// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOxrZ9lzyMYQycwVgYCl8SyWjlLjyRZBU',
    appId: '1:859031041738:web:1ff14fe363f9c41534a633',
    messagingSenderId: '859031041738',
    projectId: 'tenx-bf726',
    authDomain: 'tenx-bf726.firebaseapp.com',
    storageBucket: 'tenx-bf726.firebasestorage.app',
    measurementId: 'G-CE38K8FFQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsowrA4-FKjTM22XdDETDhHT4nkiFr_DU',
    appId: '1:859031041738:android:22c4dd1fde7f1e9434a633',
    messagingSenderId: '859031041738',
    projectId: 'tenx-bf726',
    storageBucket: 'tenx-bf726.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6_CkBgTUizmy81nflzpFmG5Jk-WWZh70',
    appId: '1:859031041738:ios:c915da9ec8406d9534a633',
    messagingSenderId: '859031041738',
    projectId: 'tenx-bf726',
    storageBucket: 'tenx-bf726.firebasestorage.app',
    iosBundleId: 'com.example.facilityErp',
  );
}
