/// Common timezones for company selection
class TimezoneData {
  static const List<Map<String, String>> timezones = [
    {'value': 'UTC', 'label': 'UTC (Coordinated Universal Time)'},
    {'value': 'America/New_York', 'label': 'America/New_York (EST/EDT)'},
    {'value': 'America/Chicago', 'label': 'America/Chicago (CST/CDT)'},
    {'value': 'America/Denver', 'label': 'America/Denver (MST/MDT)'},
    {'value': 'America/Los_Angeles', 'label': 'America/Los_Angeles (PST/PDT)'},
    {'value': 'America/Phoenix', 'label': 'America/Phoenix (MST)'},
    {'value': 'America/Anchorage', 'label': 'America/Anchorage (AKST/AKDT)'},
    {'value': 'America/Honolulu', 'label': 'America/Honolulu (HST)'},
    {'value': 'Europe/London', 'label': 'Europe/London (GMT/BST)'},
    {'value': 'Europe/Paris', 'label': 'Europe/Paris (CET/CEST)'},
    {'value': 'Europe/Berlin', 'label': 'Europe/Berlin (CET/CEST)'},
    {'value': 'Europe/Rome', 'label': 'Europe/Rome (CET/CEST)'},
    {'value': 'Europe/Madrid', 'label': 'Europe/Madrid (CET/CEST)'},
    {'value': 'Europe/Amsterdam', 'label': 'Europe/Amsterdam (CET/CEST)'},
    {'value': 'Europe/Brussels', 'label': 'Europe/Brussels (CET/CEST)'},
    {'value': 'Europe/Athens', 'label': 'Europe/Athens (EET/EEST)'},
    {'value': 'Europe/Moscow', 'label': 'Europe/Moscow (MSK)'},
    {'value': 'Asia/Dubai', 'label': 'Asia/Dubai (GST)'},
    {'value': 'Asia/Karachi', 'label': 'Asia/Karachi (PKT)'},
    {'value': 'Asia/Kolkata', 'label': 'Asia/Kolkata (IST)'},
    {'value': 'Asia/Dhaka', 'label': 'Asia/Dhaka (BST)'},
    {'value': 'Asia/Bangkok', 'label': 'Asia/Bangkok (ICT)'},
    {'value': 'Asia/Singapore', 'label': 'Asia/Singapore (SGT)'},
    {'value': 'Asia/Hong_Kong', 'label': 'Asia/Hong_Kong (HKT)'},
    {'value': 'Asia/Shanghai', 'label': 'Asia/Shanghai (CST)'},
    {'value': 'Asia/Tokyo', 'label': 'Asia/Tokyo (JST)'},
    {'value': 'Asia/Seoul', 'label': 'Asia/Seoul (KST)'},
    {'value': 'Australia/Sydney', 'label': 'Australia/Sydney (AEDT/AEST)'},
    {'value': 'Australia/Melbourne', 'label': 'Australia/Melbourne (AEDT/AEST)'},
    {'value': 'Australia/Brisbane', 'label': 'Australia/Brisbane (AEST)'},
    {'value': 'Australia/Perth', 'label': 'Australia/Perth (AWST)'},
    {'value': 'Pacific/Auckland', 'label': 'Pacific/Auckland (NZDT/NZST)'},
    {'value': 'Africa/Cairo', 'label': 'Africa/Cairo (EET/EEST)'},
    {'value': 'Africa/Johannesburg', 'label': 'Africa/Johannesburg (SAST)'},
    {'value': 'America/Sao_Paulo', 'label': 'America/Sao_Paulo (BRT/BRST)'},
    {'value': 'America/Mexico_City', 'label': 'America/Mexico_City (CST/CDT)'},
    {'value': 'America/Toronto', 'label': 'America/Toronto (EST/EDT)'},
    {'value': 'America/Vancouver', 'label': 'America/Vancouver (PST/PDT)'},
  ];
}

/// Common currencies for company selection
class CurrencyData {
  static const List<Map<String, String>> currencies = [
    {'value': 'USD', 'label': 'USD - US Dollar'},
    {'value': 'EUR', 'label': 'EUR - Euro'},
    {'value': 'GBP', 'label': 'GBP - British Pound'},
    {'value': 'JPY', 'label': 'JPY - Japanese Yen'},
    {'value': 'AUD', 'label': 'AUD - Australian Dollar'},
    {'value': 'CAD', 'label': 'CAD - Canadian Dollar'},
    {'value': 'CHF', 'label': 'CHF - Swiss Franc'},
    {'value': 'CNY', 'label': 'CNY - Chinese Yuan'},
    {'value': 'INR', 'label': 'INR - Indian Rupee'},
    {'value': 'AED', 'label': 'AED - UAE Dirham'},
    {'value': 'SAR', 'label': 'SAR - Saudi Riyal'},
    {'value': 'QAR', 'label': 'QAR - Qatari Riyal'},
    {'value': 'KWD', 'label': 'KWD - Kuwaiti Dinar'},
    {'value': 'BHD', 'label': 'BHD - Bahraini Dinar'},
    {'value': 'OMR', 'label': 'OMR - Omani Rial'},
    {'value': 'SGD', 'label': 'SGD - Singapore Dollar'},
    {'value': 'HKD', 'label': 'HKD - Hong Kong Dollar'},
    {'value': 'NZD', 'label': 'NZD - New Zealand Dollar'},
    {'value': 'ZAR', 'label': 'ZAR - South African Rand'},
    {'value': 'BRL', 'label': 'BRL - Brazilian Real'},
    {'value': 'MXN', 'label': 'MXN - Mexican Peso'},
    {'value': 'RUB', 'label': 'RUB - Russian Ruble'},
    {'value': 'KRW', 'label': 'KRW - South Korean Won'},
    {'value': 'THB', 'label': 'THB - Thai Baht'},
    {'value': 'MYR', 'label': 'MYR - Malaysian Ringgit'},
    {'value': 'IDR', 'label': 'IDR - Indonesian Rupiah'},
    {'value': 'PHP', 'label': 'PHP - Philippine Peso'},
    {'value': 'PKR', 'label': 'PKR - Pakistani Rupee'},
    {'value': 'BDT', 'label': 'BDT - Bangladeshi Taka'},
    {'value': 'EGP', 'label': 'EGP - Egyptian Pound'},
  ];
}

