ALTER TABLE users ADD COLUMN IF NOT EXISTS lease_expiry_date TIMESTAMP NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS villa_number INTEGER NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS external_id VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP NULL;
